name: programming_competition
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: 8.8.1
  url_launcher: 5.4.2
  simple_animations: 1.3.11


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Roboto Slab Black
      fonts:
        - asset: fonts/RobotoSlab-Black.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf


